# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data:rw
